---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/article_tags/{id}":
    delete:
      summary: deletes article_tags
      tags:
      - ArticleTags
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: deleted
        '404':
          description: not found
  "/article_tags":
    get:
      summary: retrieves all article_tags
      tags:
      - ArticleTags
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: lists article_tags
    post:
      summary: creates new article_tag
      tags:
      - ArticleTags
      parameters: []
      responses:
        '201':
          description: article_tag created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  article_id:
                    type: integer
                  tag_id:
                    type: integer
        '422':
          description: cannot process article_tag
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                article_id:
                  type: integer
                tag_id:
                  type: integer
              required: true
  "/articles/{id}":
    put:
      summary: updates article
      tags:
      - Articles
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: updated
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                abstract:
                  type: string
                content:
                  type: string
                url:
                  type: string
                image_url:
                  type: string
                publish_date:
                  type: string
              required: true
    delete:
      summary: deletes article
      tags:
      - Articles
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: deleted
        '404':
          description: not found
    get:
      summary: retrieves specific article
      tags:
      - Articles
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: article found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  abstract:
                    type: string
                  content:
                    type: string
                  url:
                    type: string
                  image_url:
                    type: string
                  publish_date:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
        '404':
          description: article not found
  "/article_url":
    get:
      summary: retreieve article by url
      tags:
      - Articles
      parameters:
      - name: q
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: found article
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  abstract:
                    type: string
                  content:
                    type: string
                  url:
                    type: string
                  image_url:
                    type: string
                  publish_date:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
        '404':
          description: not found
  "/articles":
    get:
      summary: retrieves all articles
      tags:
      - Articles
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: filter_ids[]
        in: query
        collectionFormat: multi
        required: false
        schema:
          type: array
      - name: filter_tag_ids[]
        in: query
        collectionFormat: multi
        required: false
        schema:
          type: array
      - name: filter_title_contains
        in: query
        required: false
        schema:
          type: string
      - name: order_by
        in: query
        required: false
        schema:
          type: string
      - name: order_direction
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: lists articles
    post:
      summary: creates an article
      tags:
      - Articles
      parameters: []
      responses:
        '201':
          description: article created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  abstract:
                    type: string
                  content:
                    type: string
                  url:
                    type: string
                  image_url:
                    type: string
                  publish_date:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
        '422':
          description: cannot process
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                abstract:
                  type: string
                content:
                  type: string
                url:
                  type: string
                image_url:
                  type: string
                publish_date:
                  type: string
              required: true
  "/tags/{id}":
    delete:
      summary: deletes tag
      tags:
      - Tags
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: deleted
        '404':
          description: not found
    put:
      summary: updates tag
      tags:
      - Tags
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: updated
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                slug:
                  type: string
              required: true
  "/tags":
    get:
      summary: retreieves all tags
      tags:
      - Tags
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: lists tags
    post:
      summary: creates new tag
      tags:
      - Tags
      parameters: []
      responses:
        '201':
          description: tag created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  slug:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                slug:
                  type: string
              required: true
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
